services:
  - type: web
    name: photo-ranking-site-v1
    env: node
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    plan: free
    envVars:
      - fromDotEnv: true
